  apache_ciphers: '-ALL:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA'
  idpconf_shibboleth_version: 'shibboleth-identity-provider-3.4.1'
  idpconf_core_sp_metadata_url: 'https://{{ int_router_host }}:{{ int_router_port }}/static/metadata/sp-metadata.xml'
  idpconf_host: '{{ hst_router_host }}'
  idpconf_scope: '{{ hst_router_host }}'
  idpconf_logo_height: '70'
  idpconf_logo_width: '229'
  idpconf_organisation_url: 'http://vm.fi/palveluarkkitehtuuri'
  idpconf_organisation_url_fi: 'http://vm.fi/palveluarkkitehtuuri'
  idpconf_organisation_url_en: 'http://vm.fi/palveluarkkitehtuuri'
  idpconf_organisation_url_sv: 'http://vm.fi/palveluarkkitehtuuri'
  idpconf_idp_shibboleth_error_tag: 'hstidpshib'
  idpconf_idp_tomcat_error_tag: 'hstidptc'
  idpconf_binding_path: 'hstidp'
  ica_dir_path: '/opt/crt/certs/icas'
  ca_dir_path: '/opt/crt/certs/ca'
  crl_dir_path: '/opt/crt/crls'
  vartti_client_url: 'https://{{ int_router_host }}:{{ int_router_port }}'
  crl_cache_timeout: '600000'
  hst_prompt_url: 'https://{{ hst_router_host }}/hstidp/hst-prompt'
  scs_enabled: 'false'
