  failure_redirect_url: 'https://{{ ext_router_host }}/sp-error'
  spconf_host: '{{ ext_router_host }}'
  spconf_service_idp_metadata_url: 'https://{{ int_router_host }}:{{ int_router_port }}/static/metadata/service-idp-metadata.xml'
  spconf_location_katso_pwd: '/LoginKatsoPWD'
  spconf_location_katso_otp: '/LoginKatsoOTP'
  spconf_location_fakevetuma: '/LoginFakevetuma'
  spconf_location_fakevetuma2: '/LoginFakevetuma2'
  spconf_location_testidp: '/LoginTestIdP'
  spconf_location_vrk: '/LoginVrk'
  spconf_location_mobiili: '/LoginMobiili'
  spconf_location_mobiili2: '/LoginMobiili2'
  spconf_location_vetuma: '/LoginVetuma'
  spconf_location_nordea: '/LoginNordea'
  spconf_AuthnContextDeclRef_nordea: 'https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.nordea.3'
  spconf_location_osuuspankki: '/LoginOsuuspankki'
  spconf_location_osuuspankki2: '/LoginOsuuspankki2'
  spconf_AuthnContextDeclRef_osuuspankki: 'https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.oko.3'
  spconf_location_alandsbanken: '/LoginAlandsbanken'
  spconf_AuthnContextDeclRef_alandsbanken: 'https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.alandsbanken.3'
  spconf_location_handelsbanken: '/LoginHandelsbanken'
  spconf_AuthnContextDeclRef_handelsbanken: 'https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.handelsbanken.3'
  spconf_location_spankki: '/LoginSpankki'
  spconf_AuthnContextDeclRef_spankki: 'https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.s-pankki.3'
  spconf_location_aktia: '/LoginAktia'
  spconf_AuthnContextDeclRef_aktia: 'https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.aktia.3'
  spconf_location_pop: '/LoginPoppankki'
  spconf_AuthnContextDeclRef_pop: 'https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.pop.3'
  spconf_location_saastopankki: '/LoginSaastopankki'
  spconf_AuthnContextDeclRef_saastopankki: 'https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.saastopankki.3'
  spconf_location_omasaastopankki: '/LoginOmasaastopankki'
  spconf_AuthnContextDeclRef_omasaastopankki: 'https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.omasaastopankki.3'
  spconf_location_danske_bank: '/LoginDanske-bank'
  spconf_AuthnContextDeclRef_danske_bank: 'https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.sampo.3'
  spconf_location_mpass: '/LoginMPASS'
  apache_ciphers: '-ALL:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA'
  apache_server_name: 'https://{{ ext_router_host }}:{{ ext_router_port }}'
  success_redirect_url: 'https://{{ ext_router_host }}'
  eidas_form_url: 'https://{{ ext_router_host }}/sivut/eidas-form/'
  eidas_email_post_url: 'https://{{ int_router_host }}:{{ int_router_port }}/feedback/eidas'
  spconf_scope: '{{ ext_router_host }}'
  spconf_organisation_url: 'http://vm.fi/palveluarkkitehtuuri'
  spconf_organisation_url_fi: 'http://vm.fi/palveluarkkitehtuuri'
  spconf_logo_height: '70'
  spconf_logo_width: '229'
  spconf_http_client_max_conn_per_route: '1024'
  spconf_http_pool_max_total: '1024'
  spconf_http_pool_default_max_per_route: '1024'
  
