  entity_id: 'https://{{ ext_router_host }}/sp2'
  spconf_support_email: 'admin@tunnistaminen.test'
  sp_key: 'sp-key.pem'
  sp_cert: 'sp-cert.pem'
  eidas_cert: 'eidas-cert.pem'
  eidas_key: 'eidas-key.pem'
  sp_eidas_signing_cert: 'sp-eidas-signing-cert.pem'
  sp_eidas_signing_key: 'sp-eidas-signing-key.pem'
  sp_eidas_encryption_cert: 'sp-eidas-encryption-cert.pem'
  sp_eidas_encryption_key: 'sp-eidas-encryption-key.pem'
  spconf_entityid_katso_pwd: "https://htesti.katso.tunnistus.fi/uas"
  spconf_AuthnContextDeclRef_katso_pwd: "https://htesti.katso.tunnistus.fi/uas/saml2/names/ac/password.katso.1"
  spconf_AuthnContextDeclRef_katso_otp: "https://htesti.katso.tunnistus.fi/uas/saml2/names/ac/otp.katso.1"
  spconf_entityid_fakevetuma: "https://shib-idp.kapa.ware.fi/idp/shibboleth"
  spconf_entityid_vrk: "https://kortti.tunnistaminen.test/hstidp/idp1"
  spconf_entityid_testidp: "https://tunnistaminen.test/testidp/idp1"
  spconf_entityid_mobiili: "https://tunnistaminen.test/mobileidp/idp1"
  spconf_entityid_mobiili2: "https://tunnistus.notreal"
  spconf_AuthnContextDeclRef_mobiili2: "https://tunnistus.notreal"
  spconf_AuthnContextDeclRef_osuuspankki2: "https://tunnistus-pp.telia.fi/uas/saml2/names/ac/saml.op.fi"
  spconf_entityid_osuuspankki2: "https://tunnistus-pp.telia.fi/uas"
  spconf_entityid_vetuma: "https://testitunnistus.suomi.fi/VETUMASSO/app"
  spconf_integrationidp_entityid: "https://tunnistaminen.test/tupasidp2"
  spconf_entityid_mpass: "https://mpass.apro.tunnistus.fi/idp/shibboleth"
  spconf_location_eidas1: "/LoginEIDAS1"
  spconf_entityid_eidas1: "https://eidas-idp.test/idp/shibboleth"
  spconf_location_eidas2: "/LoginEIDAS2"
  spconf_entityid_eidas2: "http://eidas-router:8052/EidasNode/ConnectorResponderMetadata"
  spconf_location_eidas_de: "/LoginEIDASDEeLoA3"
  spconf_location_eidas_low: "{{ spconf_location_eidas_base }}eLoA1"
  spconf_location_eidas_substantial: "{{ spconf_location_eidas_base }}eLoA2"
  spconf_location_eidas_high: "{{ spconf_location_eidas_base }}eLoA3"
  spconf_entityid_mw_de: "https://tun-kete-cache1:8037/static/metadata/service-idp-metadata.xml"
  spconf_status_acl: "127.0.0.1"
  spconf_provider_name: "DEMO-SP"
  spconf_entityid: "https://tunnistaminen.test/sp2"
  spconf_displayname: "KaPA DEV SP"
  spconf_displayname_fi: "KaPA DEV SP fi"
  spconf_displayname_en: "KaPA DEV SP en"
  spconf_displayname_sv: "KaPA DEV SP sv"
  spconf_description: "KaPA DEV SP"
  spconf_description_fi: "KaPA DEV SP desc fi"
  spconf_description_en: "KaPA DEV SP desc en"
  spconf_description_sv: "KaPA DEV SP desc sv"
  spconf_organisation_name: "KaPA e-identification development"
  spconf_organisation_name_fi: "KaPA e-identification development fi"
  spconf_organisation_name_en: "KaPA e-identification development en"
  spconf_organisation_name_sv: "KaPA e-identification development sv"
  spconf_organisation_displayname_fi: "KaPA e-identification development desc fi"
  spconf_organisation_displayname_en: "KaPA e-identification development desc en"
  spconf_organisation_displayname_sv: "KaPA e-identification development desc sv"
  spconf_organisation_url_en: "http://vm.fi/palveluarkkitehtuuri"
  spconf_organisation_url_sv: "http://vm.fi/palveluarkkitehtuuri"
  spconf_contact_given_name: "KaPA e-identification development"
  spconf_contact_surname: "KaPA e-identification development"
  spconf_subj: "/C=FI/ST=Uusimaa/L=Helsinki/O=Kapapub/OU=Kapapub/CN={{ ext_router_host }}"
  spconf_kapa_image_url: "https://{{ ext_router_host }}/static/img/kapa.png"
  spconf_contact_email: 'admin@tunnistaminen.test'
  shibgen_sp_id: "pub_core_sp"
  sp_apache_loglevel: "debug"
